language: python
sudo: false
env:
- BOTO_CONFIG=/dev/null
python:
- '3.6'
install:
- sudo apt update -y
- sudo apt install mecab libmecab-dev mecab-ipadic
- python setup.py develop -q
before_script:
- cd tests
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
